# Generated by Django 2.1.1 on 2018-10-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False)),
                ('catNombre', models.CharField(default='default', max_length=30)),
                ('catFechaCreacion', models.DateField(default='2018-09-08')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('prodNombre', models.CharField(max_length=30)),
                ('prodDescripcion', models.CharField(max_length=50)),
                ('prodPrecio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prodDisponible', models.BooleanField(default='false')),
                ('prodExistencias', models.IntegerField(default=0)),
                ('prodCatId', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Productos.Categoria')),
            ],
        ),
    ]
